# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
    exclude: .bumpversion.cfg

  - id: end-of-file-fixer

  - id: check-yaml
    args: ['--unsafe']

  - id: check-added-large-files

  - id: no-commit-to-branch
    args: ['--branch', 'main']

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.2.2
  hooks:
    - id: ruff
      args: ["--fix"]

- repo: https://github.com/psf/black
  rev: 24.2.0
  hooks:
    - id: black

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.0
  hooks:
    - id: check-github-workflows

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort

- repo: https://github.com/KyleJamesWalker/pre-commit-hooks
  rev: v0.0.4
  hooks:
    - id: todo
