name: example_dispatch

on:
  workflow_dispatch: {}

jobs:

  pr-changes:
    runs-on: ubuntu-latest

    outputs:
      matrix-params: ${{ steps.matrix-builder.outputs.matrix }}

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        id: matrix-builder
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: KyleJamesWalker/action-playground
          pr_number: 3
          default_params:
            foo: bar
            baz: qux
          inject_primary_key: project_name
          inject_params:
            example_1:
              bean: true
          extract_re: '(?P<project_name>.*)/.*'

  echo-params:
    needs: [pr-changes]

    runs-on: ubuntu-latest

    steps:
      - name: Echo outputs
        run: echo ${{ needs.pr-changes.outputs.matrix-params }}

  matrix-params:
    needs: [folder-changes]
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJson(needs.pr-changes.outputs.matrix-params ) }}

    steps:
      - name: Echo params
        run: |
          echo "${{ matrix.params.project_name }} - ${{ matrix.params.foo }}, ${{ matrix.params.baz }}, ${{ matrix.params.beans }}"
